### ISSUE TITLE
Coveralls reporting less than 1% coverage.

### ISSUE THREAD

**Issue by beporter** [loadsys/CakePHP-Stateless-Auth#24]
Because `Plugin/StatelessAuth/vendor/` is being included in the phpunit.xml.dist created by the friendsofcake/travis before_script.sh. Reference: https://coveralls.io/builds/2326241 & #23

This may be an upstream issue.

I think there needs to be an additional `<exclude>` line for `<directory suffix=\".php\">Plugin/$PLUGIN_NAME/vendor</directory>` here: https://github.com/FriendsOfCake/travis/blob/34ba1809ba8237e9486dcbccaee6d431a97497fd/before_script.sh#L95

See: https://travis-ci.org/loadsys/CakePHP-Stateless-Auth/jobs/58286758#L242

**Comment by jtyost2** [comment]
Yeah, this is an issue confirmed inside this PR: https://github.com/loadsys/CakePHP-Serializers/pull/97

**Comment by beporter** [comment]
Worked around this issue using this additional build script: https://github.com/loadsys/CakePHP-Stateless-Auth/commit/1e41f82615c0d7c559f65e8e238305c68400fdc2

Also submitted a PR to make this change "stock": https://github.com/FriendsOfCake/travis/pull/61

**Comment by beporter** [comment]
Completed in #23.
