### ISSUE TITLE
Hi friend! Some help for isAuthorized function.

### ISSUE THREAD

**Issue by fantasy2210** [loadsys/CakePHP-Stateless-Auth#29]
I got working Authentication user by nice plugin but I cant get authorized user although i have isAuthorized($user=null) function and  **$this->Auth->authorize =  array('Controller')** in controller. This is message reponse: **GET http://localhost/cakephp-api/departments.json 401 (Unauthorized)**

Please, help me!

**Comment by justinyost** [comment]
You should be able to see if your Auth User information is populated by debugging the `$user` instance from the `isAuthorized` method https://github.com/loadsys/CakePHP-Stateless-Auth/blob/master/Controller/Component/StatelessAuthComponent.php#L415

If your auth user is not populated, that needs to occur first, which might be the cause of your issues.

I would ensure that your sample requests include the tokens as documented in the sample usage section: https://github.com/loadsys/CakePHP-Stateless-Auth#sample-usage

**Comment by fantasy2210** [comment]
Thank for your fast relying, last I got working. The problems was CORS, I have OPTIONS request instead of GET because i user client at http://localhost:4200 (Angular 2) and access api service (CAKEPHP with this cool plugin). I solved that by used the client and API service with the same domain and It s woking now.
