### ISSUE TITLE
Add `coverage-ensure 100` to Travis builds.

### ISSUE THREAD

**Issue by beporter** [loadsys/CakePHP-Stateless-Auth#6]
Use `coverage-ensure` from `loadsys/cakephp-shell-scripts`?

Maybe call `composer require loadsys/cakephp-shell-scripts ~2.0` in the `.travis.yml`?

**Comment by beporter** [comment]
This is also probably going to require adding a tuned phpunit.xml file in order to exclude the Cake core and Test files themselves from the coverage report.

**Comment by beporter** [comment]
On a different topic, publishing a badge for the code coverage is going to be kind of tricky. The README needs to refer to a static image URL, which when called returns the "proper" image for the current state of coverage. This means that we have to "publish" the coverage percentage badge somewhere.

I investigated standardizing the badges as well and found this (potentially helpful) project: http://shields.io/

**Comment by jtyost2** [comment]
Also: https://coveralls.io/ for coverage

**Comment by jtyost2** [comment]
Closing as Coveralls Is Added to this repo.
